/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthSettingsImport } from './routes/_auth/settings'
import { Route as AuthInsightsImport } from './routes/_auth/insights'
import { Route as AuthDashboardImport } from './routes/_auth/dashboard'
import { Route as AuthAccountsIndexImport } from './routes/_auth/accounts/index'
import { Route as AuthAccountsAccountIdImport } from './routes/_auth/accounts/$accountId'

// Create/Update Routes

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSettingsRoute = AuthSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)

const AuthInsightsRoute = AuthInsightsImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashboardRoute = AuthDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAccountsIndexRoute = AuthAccountsIndexImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAccountsAccountIdRoute = AuthAccountsAccountIdImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardImport
      parentRoute: typeof AuthImport
    }
    '/_auth/insights': {
      id: '/_auth/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthInsightsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/accounts/$accountId': {
      id: '/_auth/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AuthAccountsAccountIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/accounts/': {
      id: '/_auth/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthAccountsIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthInsightsRoute: typeof AuthInsightsRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthAccountsAccountIdRoute: typeof AuthAccountsAccountIdRoute
  AuthAccountsIndexRoute: typeof AuthAccountsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthInsightsRoute: AuthInsightsRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthAccountsAccountIdRoute: AuthAccountsAccountIdRoute,
  AuthAccountsIndexRoute: AuthAccountsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/dashboard': typeof AuthDashboardRoute
  '/insights': typeof AuthInsightsRoute
  '/settings': typeof AuthSettingsRoute
  '/accounts/$accountId': typeof AuthAccountsAccountIdRoute
  '/accounts': typeof AuthAccountsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/dashboard': typeof AuthDashboardRoute
  '/insights': typeof AuthInsightsRoute
  '/settings': typeof AuthSettingsRoute
  '/accounts/$accountId': typeof AuthAccountsAccountIdRoute
  '/accounts': typeof AuthAccountsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/insights': typeof AuthInsightsRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/accounts/$accountId': typeof AuthAccountsAccountIdRoute
  '/_auth/accounts/': typeof AuthAccountsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/logout'
    | '/dashboard'
    | '/insights'
    | '/settings'
    | '/accounts/$accountId'
    | '/accounts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/logout'
    | '/dashboard'
    | '/insights'
    | '/settings'
    | '/accounts/$accountId'
    | '/accounts'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/logout'
    | '/_auth/dashboard'
    | '/_auth/insights'
    | '/_auth/settings'
    | '/_auth/accounts/$accountId'
    | '/_auth/accounts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login",
        "/logout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/dashboard",
        "/_auth/insights",
        "/_auth/settings",
        "/_auth/accounts/$accountId",
        "/_auth/accounts/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/_auth/dashboard": {
      "filePath": "_auth/dashboard.tsx",
      "parent": "/_auth"
    },
    "/_auth/insights": {
      "filePath": "_auth/insights.tsx",
      "parent": "/_auth"
    },
    "/_auth/settings": {
      "filePath": "_auth/settings.tsx",
      "parent": "/_auth"
    },
    "/_auth/accounts/$accountId": {
      "filePath": "_auth/accounts/$accountId.tsx",
      "parent": "/_auth"
    },
    "/_auth/accounts/": {
      "filePath": "_auth/accounts/index.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
