name: Docker Image CI

on:
  push:
    branches: [ "main", "chore/actions" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Checks out your repository code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 # Sets up Docker Buildx for multi-platform builds

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }} # Your Docker Hub username (stored as a GitHub secret)
    #     password: ${{ secrets.DOCKER_PASSWORD }} # Your Docker Hub Access Token/Password (stored as a GitHub secret)

    # - name: Extract branch name (for dynamic image naming)
    #   id: extract_branch
    #   run: echo "::set-output name=branch::$(echo '${{ github.head_ref }}' | sed 's/[^a-zA-Z0-9-]//g' | tr '[:upper:]' '[:lower:]')"

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: . # The build context (usually the root of your repo)
        push: false # Specifies that the image should be pushed to the registry
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/balance-ui:latest
          ${{ secrets.DOCKER_USERNAME }}/balance-ui:${{ github.event.number }}

        # Optionally add build arguments, e.g.:
        # build-args: |
        #   VERSION=${{ github.event.number }}
        # cache-from: type=gha # Optional: Cache layers for faster builds
        # cache-to: type=gha,mode=max # Optional: Cache layers for faster builds